# Generated by Django 4.0.1 on 2022-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='languageDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0)),
                ('reliable', models.BooleanField()),
            ],
        ),
    ]
