version: '3.8'
services:
 app:
  build: .
  volumes:
   - .:/app
  ports:
   - 8080:8080
  image: application:django
  container_name: app_container
  command: gunicorn project.wsgi:application --bind 0.0.0.0:8080 --workers 1 -threads 8 app:app 